#!/usr/bin/env python3
"""
Assemble REPORT.md: a single Markdown page with the key summary-stats
tables and time-series charts, meant to be read directly on GitHub (which
renders Markdown tables and embedded images automatically).

Regenerates the two time-series charts (using each plotting script's
default countries) and embeds them alongside markdown-formatted versions
of the descriptive-stats, correlation, and top-country-year tables from
summarize_panel.py. Run this after build_panel.py.
"""
from __future__ import annotations

from pathlib import Path

import plot_all_series_timeseries as past
import plot_strikes_timeseries as pst
import summarize_panel as sp

HERE = Path(__file__).resolve().parent
REPORT_PATH = HERE / "REPORT.md"


def md_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def overall_stats_table(rows: list[dict]) -> list[str]:
    out_rows = []
    for col in sp.VARS:
        vals = sorted(v for v in (r[col] for r in rows) if v is not None)
        n = len(vals)
        missing = len(rows) - n
        if n:
            mean = sum(vals) / n
            sd = (sum((x - mean) ** 2 for x in vals) / (n - 1)) ** 0.5 if n > 1 else float("nan")
            median = vals[n // 2] if n % 2 else (vals[n // 2 - 1] + vals[n // 2]) / 2
            mn, mx = vals[0], vals[-1]
        else:
            mean = sd = median = mn = mx = float("nan")
        out_rows.append(
            [
                sp.VAR_LABELS[col],
                str(n),
                str(missing),
                f"{mean:,.2f}",
                f"{sd:,.2f}",
                f"{mn:,.2f}",
                f"{median:,.2f}",
                f"{mx:,.2f}",
            ]
        )
    return md_table(["Variable", "N", "Missing", "Mean", "SD", "Min", "Median", "Max"], out_rows)


def correlation_table(rows: list[dict]) -> list[str]:
    out_rows = []
    for c1 in sp.VARS:
        row_vals = [sp.VAR_SHORT[c1]]
        for c2 in sp.VARS:
            paired = [(r[c1], r[c2]) for r in rows if r[c1] is not None and r[c2] is not None]
            if len(paired) < 2:
                row_vals.append("n/a")
                continue
            xs, ys = zip(*paired)
            row_vals.append(f"{sp.pearson(list(xs), list(ys)):.2f}")
        out_rows.append(row_vals)
    return md_table(["", *[sp.VAR_SHORT[c] for c in sp.VARS]], out_rows)


def top_table(rows: list[dict], col: str, top_n: int = 10) -> list[str]:
    ranked = sorted((r for r in rows if r[col] is not None), key=lambda r: r[col], reverse=True)
    out_rows = [[r["ref_area"], str(r["time"]), f"{r[col]:,.0f}"] for r in ranked[:top_n]]
    return md_table(["Country", "Year", sp.VAR_LABELS[col]], out_rows)


def main() -> int:
    rows = sp.load_panel()

    print("Regenerating charts...")
    strikes_png = pst.OUT_DIR / "strikes_timeseries_de_fr_uk_us.png"
    pst.plot(pst.load_series(pst.DEFAULT_COUNTRIES), strikes_png)

    all_png = past.OUT_DIR / "timeseries_all_indicators.png"
    past.plot(past.load_data(past.DEFAULT_COUNTRIES), past.DEFAULT_COUNTRIES, all_png)

    years = [r["time"] for r in rows]
    lines: list[str] = []
    lines.append("# ILOSTAT Industrial Disputes — Results")
    lines.append("")
    lines.append(
        "Auto-generated by `generate_report.py` from `processed/industrial_disputes_panel.csv`. "
        "Do not edit by hand — re-run the script after the data changes."
    )
    lines.append("")
    lines.append(
        f"**Coverage**: {len(rows):,} country-year rows, "
        f"{len(set(r['ref_area'] for r in rows))} countries/territories, "
        f"{min(years)}–{max(years)}."
    )
    lines.append("")
    lines.append("## Summary statistics")
    lines.append("")
    lines += overall_stats_table(rows)
    lines.append("")
    lines.append("## Correlations")
    lines.append("")
    lines.append("Pairwise correlations (pairwise-complete observations).")
    lines.append("")
    lines += correlation_table(rows)
    lines.append("")
    lines.append("## Biggest recorded disputes")
    lines.append("")
    lines.append("### By number of strikes/lockouts")
    lines.append("")
    lines += top_table(rows, "n_strikes_lockouts")
    lines.append("")
    lines.append("### By days not worked")
    lines.append("")
    lines += top_table(rows, "days_not_worked")
    lines.append("")
    lines.append("## Time series")
    lines.append("")
    lines.append(f"![Number of strikes/lockouts]({strikes_png.relative_to(HERE).as_posix()})")
    lines.append("")
    lines.append(f"![All four indicators]({all_png.relative_to(HERE).as_posix()})")
    lines.append("")

    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
